name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: dart pub publish --force